CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id bigint(20) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);